#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AnimationDrawableTest.Resource", IsApplication=true)]

namespace AnimationDrawableTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fat_po = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fat_po_f01 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fat_po_f02 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int fat_po_f03 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int fat_po_f04 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int fat_po_f05 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int fat_po_f06 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int fat_po_f07 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int fat_po_f08 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int fat_po_f09 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int fat_po_f10 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int fat_po_f11 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int fat_po_f12 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int fat_po_f13 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int fat_po_f14 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int fat_po_f15 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int fat_po_f16 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int fat_po_f17 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int fat_po_f18 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int fat_po_f19 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int fat_po_f20 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int fat_po_f21 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int fat_po_f22 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int fat_po_f23 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int fat_po_f24 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int fat_po_f25 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int fat_po_f26 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int fat_po_f27 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_launcher = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Icon = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int anim = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int btn_paly = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int btn_stop = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
